server {
    listen 80;
    listen [::]:80;
    server_name botsync.ru;
    root /var/www/html/public;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    index index.php;

    charset utf-8;

    # Laravel API (apa & api)
    location ~ ^/(api) {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Laravel Cabinet & Tools
    location ~ ^/(dashboard|horizon|up) {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Laravel Admin
    location ~ ^/(admin) {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Laravel Assets (Vite)
    location /build/ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
        access_log off;
    }


    # Default: Proxy to Astro
    location / {
        proxy_pass http://service-botsync-web-yejqlx:4321; # Используйте имя сервиса из Dokploy и порт 4321
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Обработка ошибок прокси (если Astro недоступен, можно отдать 502 или попробовать Laravel)
        proxy_intercept_errors on;
        error_page 502 = @laravel;
    }

    location @laravel {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_hide_header X-Powered-By;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }

    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css text/xml application/json application/javascript application/rss+xml application/atom+xml image/svg+xml;
}
